$(".runb").click(function(){
    $(".runt").slideToggle();
});
$(".bikeb").click(function(){
    $(".biket").slideToggle();
});
$(".powerb").click(function(){
    $(".powert").slideToggle();
});
$(".otherb").click(function(){
    $(".othert").slideToggle();
});